server:
  port: 8086

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  exchangeList: '/exchanges'
  exchangeListMarket: '/list'
  exchangeById: '/{idMarket}'
  exchangeTickerById: '/{idMarket}/tickers'
  exchangeVolumeChart: '/{idMarket}/volumeChart'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  exchangeList: '/exchanges'
  exchangeListMarket: '/list'
  exchangeById: '/%s'
  exchangeTickerById: '/%s/tickers'
  exchangeVolumeChart: '/%s/volume_chart'
